"""
Website Fingerprint engine — the core "Vibe-Coded Website Detector" logic.

Detects whether a *website* (not its written content) looks like it was
scaffolded by an AI website builder (Lovable, Bolt, v0, Cursor, Replit, etc.)
rather than hand-built.

Signals, roughly ordered strongest -> weakest:
1. Hosting/domain pattern   — the URL itself is on a known AI-builder domain
                               (lovable.app, bolt.new preview, etc.) — this
                               alone is close to a smoking gun
2. Signature comments/phrases — AI-builder phrases left in source/comments
3. Placeholder/boilerplate text — unedited template content ("Edit this
                               text", generic Lorem Ipsum, default titles)
4. Library fingerprint      — known AI-tool default stack signatures
5. Tailwind density         — ratio of Tailwind utility classes to total
6. File-naming pattern      — generic vs descriptive file/script names
7. Meta-generator fingerprint
8. Exposed sourcemaps       — .map files left in a preview/dev deployment
9. CSS custom-property usage — hand-tuned design systems define their own
                               --tokens; AI scaffolds usually don't

Important note on `html`: this is expected to be the *rendered* HTML (after
JavaScript has run), fetched via a headless browser in url_scraper.py — not
the raw server response. AI-builder output is almost always a React/Next
SPA, so the raw pre-JS HTML is often just an empty shell and badly
undercounts every DOM-based signal (Tailwind density, file-naming, etc.).
"""
import re
from urllib.parse import urlparse

from app.engines.base import Engine, EngineOutput

SIGNATURE_PHRASES = [
    "generated by lovable",
    "built with bolt",
    "built with v0",
    "made with v0",
    "created with cursor",
    "powered by lovable",
    "bolt.new",
    "lovable.dev",
    "v0.dev",
    "generated with claude",
    "built with claude code",
    "windsurf",
    "generated by replit",
    "made in webflow",
]

# Domains AI website builders publish/preview to. A URL living on one of
# these is a near-direct signal — no DOM inspection needed.
AI_BUILDER_DOMAINS = [
    "lovable.app", "lovableproject.com",
    "bolt.new", "bolt.host",
    "v0.dev", "v0.app",
    "vercel.app",       # also used by many hand-built Next.js sites — weaker on its own
    "netlify.app",      # same caveat
    "webcontainer-api.io",
    "replit.app", "replit.dev", "repl.co",
    "webflow.io",
    "framer.website", "framer.app",
]
# Domains that are common AI-builder hosts but also extremely common for
# regular hand-built projects — treated as a weaker signal than the rest.
AMBIGUOUS_HOST_DOMAINS = {"vercel.app", "netlify.app"}

PLACEHOLDER_PHRASES = [
    "lorem ipsum",
    "edit this text",
    "your company name",
    "your site title",
    "click to edit",
    "sample text",
    "placeholder text",
    "add your text here",
    "this is a placeholder",
]

KNOWN_LIBRARY_SIGNATURES = {
    "tailwind": [r"tailwindcss", r"tailwind\.config"],
    "shadcn/ui": [r"shadcn", r"class-variance-authority", r"cva\("],
    "radix ui": [r"@radix-ui", r"radix-"],
    "next.js scaffold": [r"__next", r"_next/static", r"next/dist"],
    "vite default scaffold": [r"vite\.svg", r"/@vite/client"],
}

GENERIC_NAME_PATTERN = re.compile(
    r"^(component|chunk|index|main|app|page|bundle|module)[-_.]?[0-9a-f]{0,10}\.(js|jsx|ts|tsx)$",
    re.IGNORECASE,
)
HASHED_ASSET_PATTERN = re.compile(r"[-.][0-9a-f]{8,}\.(js|css)$", re.IGNORECASE)

TAILWIND_UTILITY_PATTERN = re.compile(
    r"^(sm:|md:|lg:|xl:|2xl:|hover:|focus:|dark:)?"
    r"(flex|grid|block|inline|hidden|p[trblxy]?-\d+|m[trblxy]?-\d+|"
    r"w-|h-|bg-|text-|font-|border|rounded|shadow|gap-\d+|items-|justify-|"
    r"space-[xy]-\d+|max-w-|min-w-|opacity-\d+|z-\d+|top-|left-|right-|bottom-)"
)


def _extract_class_names(html: str) -> list[str]:
    classes = []
    for match in re.finditer(r'class(?:Name)?="([^"]+)"', html):
        classes.extend(match.group(1).split())
    return classes


def _extract_script_and_link_names(html: str) -> list[str]:
    names = []
    for match in re.finditer(r'(?:src|href)="([^"]+\.(?:js|jsx|ts|tsx|css))"', html):
        path = match.group(1)
        names.append(path.rsplit("/", 1)[-1])
    return names


class WebsiteFingerprintEngine(Engine):
    engine_id = "website_fingerprint"
    engine_name = "Website Fingerprint"
    category = "website"
    weight = 1.0

    def applies_to(self, input_type: str) -> bool:
        return input_type == "url"

    def run(self, *, text: str = "", html: str = "", url: str = "", raw_html_before_js: str = "") -> EngineOutput:
        html_lower = html.lower()
        raw_lower = raw_html_before_js.lower()
        combined_lower = html_lower + " " + raw_lower  # signature phrases can hide in either
        signals: dict = {}
        score_breakdown: dict = {}
        points = 0.0
        max_points = 0.0

        # 1. Hosting/domain pattern — strongest, cheapest signal
        max_points += 25
        host = urlparse(url).hostname or ""
        matched_domain = next((d for d in AI_BUILDER_DOMAINS if host.endswith(d)), None)
        if matched_domain:
            domain_points = 15 if matched_domain in AMBIGUOUS_HOST_DOMAINS else 25
            points += domain_points
            score_breakdown["hosting_domain"] = domain_points
        else:
            score_breakdown["hosting_domain"] = 0
        signals["hosting_domain_match"] = matched_domain

        # 2. Signature comments / phrases
        max_points += 20
        found_phrases = [p for p in SIGNATURE_PHRASES if p in combined_lower]
        signature_points = 20 if found_phrases else 0
        points += signature_points
        score_breakdown["signature_phrases"] = signature_points
        signals["signature_phrases_found"] = found_phrases

        # 3. Placeholder/boilerplate text
        max_points += 10
        found_placeholders = [p for p in PLACEHOLDER_PHRASES if p in html_lower]
        placeholder_points = 10 if found_placeholders else 0
        points += placeholder_points
        score_breakdown["placeholder_text"] = placeholder_points
        signals["placeholder_phrases_found"] = found_placeholders

        # 4. Library fingerprint
        max_points += 15
        matched_libs = []
        for lib_name, patterns in KNOWN_LIBRARY_SIGNATURES.items():
            if any(re.search(p, combined_lower) for p in patterns):
                matched_libs.append(lib_name)
        library_points = min(15, len(matched_libs) * 5)
        points += library_points
        score_breakdown["library_fingerprint"] = library_points
        signals["matched_libraries"] = matched_libs

        # 5. Tailwind density
        max_points += 15
        classes = _extract_class_names(html)
        density = (
            sum(1 for c in classes if TAILWIND_UTILITY_PATTERN.match(c)) / len(classes)
            if classes else 0.0
        )
        if density > 0.6:
            tailwind_points = 15
        elif density > 0.35:
            tailwind_points = 8
        else:
            tailwind_points = 0
        points += tailwind_points
        score_breakdown["tailwind_density"] = tailwind_points
        signals["tailwind_density"] = round(density, 3)

        # 6. File-naming pattern
        max_points += 10
        asset_names = _extract_script_and_link_names(html)
        generic_ratio = (
            sum(1 for n in asset_names if GENERIC_NAME_PATTERN.match(n) or HASHED_ASSET_PATTERN.search(n))
            / len(asset_names)
            if asset_names else 0.0
        )
        if generic_ratio > 0.7:
            naming_points = 10
        elif generic_ratio > 0.4:
            naming_points = 5
        else:
            naming_points = 0
        points += naming_points
        score_breakdown["file_naming"] = naming_points
        signals["generic_filename_ratio"] = round(generic_ratio, 3)
        signals["assets_seen"] = asset_names[:15]

        # 7. Meta-generator fingerprint
        max_points += 5
        generator_match = re.search(r'<meta[^>]+name="generator"[^>]+content="([^"]+)"', html, re.IGNORECASE)
        meta_points = 5 if generator_match else 0
        points += meta_points
        score_breakdown["meta_generator"] = meta_points
        signals["meta_generator"] = generator_match.group(1) if generator_match else None

        # 8. Exposed sourcemaps
        max_points += 5
        has_sourcemap = bool(re.search(r"\.js\.map|sourceMappingURL", html))
        sourcemap_points = 5 if has_sourcemap else 0
        points += sourcemap_points
        score_breakdown["exposed_sourcemap"] = sourcemap_points
        signals["sourcemap_exposed"] = has_sourcemap

        # 9. CSS custom-property usage (fewer = more likely default scaffold)
        max_points += 5
        custom_prop_count = len(re.findall(r"--[a-zA-Z0-9-]+\s*:", html))
        if custom_prop_count == 0:
            custom_prop_points = 5
        elif custom_prop_count < 5:
            custom_prop_points = 2
        else:
            custom_prop_points = 0
        points += custom_prop_points
        score_breakdown["css_custom_properties"] = custom_prop_points
        signals["css_custom_properties_found"] = custom_prop_count

        overall_score = (points / max_points) * 100 if max_points else 0.0

        # Coverage/confidence: if we barely found any classes or assets even
        # after JS rendering, the page may have failed to render fully (SPA
        # still loading, bot-blocked, unusual framework) — flag this rather
        # than silently reporting a confidently low score.
        low_coverage = len(classes) < 5 and len(asset_names) < 2
        if low_coverage:
            confidence = "low"
        elif len(classes) > 30 and asset_names:
            confidence = "high"
        else:
            confidence = "medium"

        summary_bits = []
        if matched_domain:
            summary_bits.append(f"hosted on a known AI-builder domain ({matched_domain})")
        if found_phrases:
            summary_bits.append(f"AI-builder signature phrase(s) found: {', '.join(found_phrases)}")
        if found_placeholders:
            summary_bits.append("unedited placeholder text still present")
        if matched_libs:
            summary_bits.append(f"matches default stack: {', '.join(matched_libs)}")
        summary_bits.append(f"Tailwind density {density:.0%}")
        if low_coverage:
            summary_bits.append("⚠ very little rendered content was found — treat this score with caution")
        summary = "; ".join(summary_bits) if summary_bits else "No strong AI-builder signals detected."

        signals["score_breakdown"] = score_breakdown
        signals["max_points_possible"] = max_points

        return EngineOutput(
            engine_id=self.engine_id,
            engine_name=self.engine_name,
            category=self.category,
            score=overall_score,
            confidence=confidence,
            summary=summary,
            details=signals,
        )
